<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <form id="form2" runat="server">
    <div>
    
        <center>
        <h1>
        Student Data
    </h1>
        <asp:GridView ID="GridView1" runat="server" AllowSorting="True" 
            AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" DataKeyNames="id" 
            DataSourceID="SqlDataSource1" onrowupdating="GridView1_RowUpdating" 
            onselectedindexchanged="GridView1_SelectedIndexChanged" CellPadding="10" 
                CellSpacing="10" Width="829px">
            <Columns>
                 <asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" 
                    SortExpression="id" />
                <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />
                <asp:BoundField DataField="city" HeaderText="city" SortExpression="city" />
                <asp:BoundField DataField="state" HeaderText="state" SortExpression="state" />
                <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
                
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
            SelectCommand="SELECT * FROM [stud]" 
            DeleteCommand="DELETE FROM stud WHERE id = @id" 
            UpdateCommand="UPDATE stud SET name = @name, city = @city, state = @state, email = @email WHERE id = @id">
            <DeleteParameters>
                <asp:ControlParameter ControlID="GridView1" Name="id" 
                    PropertyName="SelectedValue" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:ControlParameter ControlID="GridView1" Name="name" 
                    PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="GridView1" Name="city" 
                    PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="GridView1" Name="state" 
                    PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="GridView1" Name="email" 
                    PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="GridView1" Name="id" 
                    PropertyName="SelectedValue" />
            </UpdateParameters>
        </asp:SqlDataSource>
      </center>  
    </div>
    </form>
    </div>
    </form>
</body>
</html>
