IF NOT EXISTS (SELECT * FROM sys.change_tracking_databases WHERE database_id = DB_ID(N'D:\MADI\LOGIN\LOGIN\PRO.MDF')) 
   ALTER DATABASE [D:\MADI\LOGIN\LOGIN\PRO.MDF] 
   SET  CHANGE_TRACKING = ON
GO
